#pragma once

#include <vector>

class RenderJob;
class Camera;
class PointLight;

using namespace std;

/*
* Class containing information needed by renderer.
*/
class RenderInformation
{
	public:
		/*
		* Constructor. 
		* vector<Camera *> *cameras - Vector of cameras in scene.
		* vector<RenderJob *> renderJobs - Vector of render jobs generated by scene. 
		*/
		RenderInformation(vector<Camera *> *cameras, vector<RenderJob *> *renderJobs, vector<PointLight *> *pointLights);

		/*
		* Get the cameras to render from. 
		*/
		vector<Camera *> *getCameras();

		/*
		* Get the render jobs to render. 
		*/
		vector<RenderJob *> *getRenderJobs();

		/*
		* Get the point lights in the scene.
		*/
		vector<PointLight *> *getPointLights();

	private:
		vector<Camera *> *_cameras;
		vector<RenderJob *> *_renderJobs;
		vector<PointLight *> *_pointLights;
};